### PR TITLE
Upgrade stack to Pytorch 2.0 + CUDA 11.7 + TRT 8.5 GA 

### PR DESCRIPTION
**Pull request by peri044**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by yinghai — COMMENTED** [review]
Please rebase against master. And failure of ATenStackPureTensorConvertsCorrectly seems legit.

**Comment by peri044** [comment]
> @peri044 retarget this PR to release/1.3, we will cherry pick into master from there

Opened a new PR for this https://github.com/pytorch/TensorRT/pull/1485

**Comment by narendasan** [comment]
@peri044 some of these changes overwrite the new PyTorch version

**Review by narendasan — APPROVED** [review]
LGTM, the docs changes seem unnecessary but i think the CI will take care of it

**Pull request merged**
