### PR TITLE
fix: FakeTensors appearing in `get_attr` calls

### LINKED ISSUE #2658: 🐛 [Bug] Issue in conversion when parameters/buffers are moved during compilation
### Bug 1
```python
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch_tensorrt/dynamo/conversion/converter_utils.py", line 491, in to_numpy
    output = value.cpu().detach().contiguous().numpy()
RuntimeError: .numpy() is not supported for tensor subclasses.
```
### Suggested Fix 1
Need a custom version of the following function which registers a parameter, not a buffer
https://github.com/pytorch/TensorRT/blob/afd5abebbffa49107bcc7766c9f00bd6be2e593c/py/torch_tensorrt/dynamo/lowering/passes/constant_folding.py#L39

### Bug 2
```python
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_ops.py", line 571, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and meta! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```
### Suggested Fix 2
Need to cast constant Tensors to `nn.Parameter` on `CUDA` at constant-folding time
https://github.com/pytorch/TensorRT/blob/afd5abebbffa49107bcc7766c9f00bd6be2e593c/py/torch_tensorrt/dynamo/lowering/passes/constant_folding.py#L39

### Bug 3
```python
File "<eval_with_key>.67 from /root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py:569 in wrapped", line 11, in forward
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_ops.py", line 571, in __call__
  return self_._op(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and meta! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```
### Suggested Fix 3
This line needs to be removed, as it has unintended behavior when casting constant params
https://github.com/pytorch/TensorRT/blob/afd5abebbffa49107bcc7766c9f00bd6be2e593c/py/torch_tensorrt/dynamo/conversion/_conversion.py#L32

## Expected behavior

Model should compile

## Environment

 - Torch and Torch-TensorRT Version: `2.3.0.dev2024222+cu121`

### PR DESCRIPTION
**Pull request by gs-olive**
# Description

- Register all constants as model parameters, which do not get fake-ified by the active FakeTensor context
- Buffers and other constant registrations can be fake-ified, which is problematic for TRT tracing

Fixes #2658

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ - ] I have added tests to verify my fix or my feature
  - Pending CI verification on existing models
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by zewenli98 — APPROVED** [review]
Looks good to me! I'm just wondering if PyTorch has documentation to illustrate what kind of types will be fake-ified?

**Comment by gs-olive** [comment]
Thanks for the review - I haven't found any concrete documentation on this topic; this is mainly a workaround that I've found to work for a few key models and not break others. [This documentation](https://github.com/pytorch/pytorch/blob/a656e12bf5851d21ba6a3e73b479de3e0cad8113/docs/source/torch.compiler_fake_tensor.rst#L47) on `FakeTensor` is what I am using currently.

**Review by bowang007 — APPROVED** [review]
LGTM.

**Comment by bowang007** [comment]
@gs-olive  can you merge this one? 
This can make us a lot easier every time using the nightly container. 
Thanks!

**Comment by gs-olive** [comment]
Since testing is not working in CI, running the Dynamo test suite locally to verify

**Pull request merged**
