### PR TITLE
fix: Update broken repo hyperlink

### PR DESCRIPTION
**Pull request by lamhoangtung**
# Description

Hi, I'm looking in the new documentation over at https://pytorch.org/TensorRT/ and found some hyperlink broken for the torchtrt_runtime example and decided to do a quick PR to fix it.

I also found a bunch of old link to this repo and updated it with the new repo link under pytorch organization 

## Type of change
- This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
Can you drop changes to `//docs` from this PR? Our CI will build a new version once its checked into master and it will make this PR much easier to review.

**Comment by narendasan** [comment]
Hmm the docs changes are still around, can you drop any changes to docs and rebase on master? Or tt might be easier to do this on a new branch and open a new PR

**Comment by lamhoangtung** [comment]
@narendasan. Seems like the changes to docs are autogenerated. Sure. Let me open a new PR

**Comment by lamhoangtung** [comment]
@narendasan can you take a look at the new PR #1131

**Pull request closed without merging**
