### PR TITLE
Stack upgrade to latest pytorch nightly

### PR DESCRIPTION
**Pull request by peri044**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
How do we guarantee that versions will be aligned between C++ and Python, CI and local?

**Comment by peri044** [comment]
> How do we guarantee that versions will be aligned between C++ and Python, CI and local?

Only raised this PR for a check with latest nightly for DLFW task. The guarantee comes basically from Pytorch itself.

**Comment by narendasan** [comment]
nightly latest will move ahead very quickly, does not seem like a good idea to use it

**Comment by peri044** [comment]
This PR is not intended to merge. But only a one off test with nightly. Closing this

**Pull request closed without merging**
