### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by frank-wei**
Update to 20230312 to include the fixes for flaky tests introduced by dynamo

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by narendasan — APPROVED** [review]
LGTM

**Comment by narendasan** [comment]
@frank-wei any idea why the CI cant pull the new build?

**Comment by gs-olive** [comment]
The new Torch version may also need to be added to `py/requirements.txt`

**Comment by frank-wei** [comment]
> The new Torch version may also need to be added to `py/requirements.txt` + `tests/modules/requirements.txt`. Also it seems that as of Mar 2, the versions on https://download.pytorch.org/whl/nightly/torch/ have switched to version `2.1.0`, instead of `2.0.0`.

yes, it looks like changed to 2.1 as  torch-2.1.0.dev20230314

**Pull request merged**
