### PR TITLE
Upstream 3 features to fx_ts_compat: MS, VC, Optimization Level

### PR DESCRIPTION
**Pull request by wu6u3tw**
# Description
- Max Stream,
- Version Compatability
- Optimization Level

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by wu6u3tw** [comment]
@narendasan @nvpohanh for viz

**Comment by nvpohanh** [comment]
LGTM

**Comment by narendasan** [comment]
@dheerajperi can you review?

**Comment by nvpohanh** [comment]
@peri044 @narendasan Could you review? This is the same as #1926

**Comment by nvpohanh** [comment]
@narendasan Could you merge this? We don't have the permission. Thanks

**Pull request merged**
