### PR TITLE
feat: Fixed conv1d converter when weights are Tensor

### PR DESCRIPTION
**Pull request by andi4191**
# Description

This PR enables the conv1d -> conv2d converter mapping work when the weights are Tensor.
PS: Kernel tensor is also unsqueezed when the filterDims are unsqueezed for conv1d -> conv2d scenario.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by andi4191** [comment]
@apbose : I see my PR is breaking in CI. Is the CI broken? I see some torch-tensorrt dependency related issue in the workflow run.

**Comment by peri044** [comment]
@andi4191  There was a problem with CI. I re-triggered it to verify if the latest changes fixed it.

**Comment by peri044** [comment]
@andi4191  Can you rebase your changes and resolve conflicts ?

**Comment by andi4191** [comment]
> @andi4191 Can you rebase your changes and resolve conflicts ?

Thanks, I resolved the conflicts. However, I still see CI build failure.

**Comment by bowang007** [comment]
> @bowang007 : Is there anything that I can do to merge this PR? Any update on the root cause for CI failure?

Hi @andi4191 thanks for supporting this. 
I think we have removed the CI test for torchscript, correct me if I'm wrong @narendasan. 
I'll take a look at this PR tonight and test locally, then I think it should be good to merge. 

Thanks!

**Comment by andi4191** [comment]
> > @bowang007 : Is there anything that I can do to merge this PR? Any update on the root cause for CI failure?
> 
> Hi @andi4191 thanks for supporting this. I think we have removed the CI test for torchscript, correct me if I'm wrong @narendasan. I'll take a look at this PR tonight and test locally, then I think it should be good to merge.
> 
> Thanks!

Thank you for the update @bowang007

**Comment by andi4191** [comment]
Hi @bowang007,

Is this PR good to merge now?

**Review by bowang007 — APPROVED** [review]
LGTM

**Pull request merged**
