### PR TITLE
fix: bug in elementwise base for static inputs

### PR DESCRIPTION
**Pull request by zewenli98**
# Description

Fixes #2774 #2726 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by chohk88** [comment]
This looks good to me. It seems like it could resolve the CI/CD issues mentioned in [2726](https://github.com/pytorch/TensorRT/pull/2726)

**Comment by chohk88** [comment]
It seems that we've encountered an accuracy issue in the CI/CD test, which wasn't quite what we expected. Could this be the error you mentioned occurring in TRT-10?

**Comment by zewenli98** [comment]
> Could this be the error you mentioned occurring in TRT-10?

@chohk88 Yes that's it! The issue here is that the original `broadcast()` function in `fx/conterver_utils.py` only broadcasts two ITensors to the same number of dimensions (ranks) by prepending 1s, which results in the error in the following `ctx.net.add_elementwise()`. For fixing this, I wrote another similar broadcast function, called `broadcast_to_same_shape` that can broadcast two ITensors to the exactly same shape.

For example, we have original ITensors: lhs_val.shape: (2, 3) rhs_val.shape: (2, 2, 1, 3)
- If calling fx/converter_utils.broadcast, lhs_val.shape: (1, 1, 2, 3) lhs_val.shape: (2, 2, 1, 3).
- If calling broadcast_to_same_shape, lhs_val.shape: (2, 2, 2, 3) lhs_val.shape: (2, 2, 2, 3).

I think this fix should also work for #2726

**Comment by chohk88** [comment]
This looks good to me.

**Comment by zewenli98** [comment]
@peri044 Is this PR needed to be cherry-picked to `release/2.3`?

**Pull request merged**
