### PR TITLE
feat (//core/conversion) : Add converter for torch.bitwise_not

### PR DESCRIPTION
**Pull request by blchu**
# Description

Add converter for torch.bitwise_not

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by blchu** [comment]
Could I get approval to run workflows?

**Review by peri044 — APPROVED** [review]
LGTM

**Review by bowang007 — APPROVED** [review]

**Comment by peri044** [comment]
@blchu Can you fix the linter issue by running the following ? 
`bazel run //tools/linter:cpplint -- //...`

**Comment by blchu** [comment]
The linter is changing files that I hadn't modified or added, would that be a concern?

**Pull request merged**
