### PR TITLE
Added QAT/PTQ workflow example

### PR DESCRIPTION
**Pull request by anniesurla**
# Description

Added an example notebook to demonstrate the workflow of PTQ and QAT using Torch-TensorRT

## Type of change
-New Example

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
IMO even if it results in a more verbose notebook it's better to have all the necessary code in the notebook instead of shipping a utility file as well because this makes it harder for someone to pull the notebook out of the repo and run it independently. Notebooks should try to be as self contained as possible

**Comment by anniesurla** [comment]
@narendasan Davide suggested Tanay upload the notebook since the CLA process can take sometime. Since Tanay is all set as contributor, he will be uploading this on my behalf. You can however suggest all changes, I will make them accordingly, and when ready, Tanay will submit a new PR.

**Review by narendasan — COMMENTED** [review]
These changes look good to me, feel free to close and have @tanayvarshney open a PR from this branch

**Review by narendasan — APPROVED** [review]

**Comment by narendasan** [comment]
Merged in #1239

**Pull request closed without merging**
