### PR TITLE
[feat] Add support for argmax and argmin

### PR DESCRIPTION
**Pull request by mfeliz-cruise**
Adds support for aten::argmax and aten::argmin.

Fixes # (issue)

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.

**Comment by mfeliz-cruise** [comment]
> Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.

ATenMaxDimConvertsCorrectly was already in the topk tests so I followed that pattern for the rest of the file.

**Comment by mfeliz-cruise** [comment]
> Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.

In my environment `clang-format tests/core/conversion/converters/test_topk.cpp -i` is not making any changes. Is there a good way to see what the github linter is complaining about?

**Comment by narendasan** [comment]
> > Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.
> 
> In my environment `clang-format tests/core/conversion/converters/test_topk.cpp -i` is not making any changes. Is there a good way to see what the github linter is complaining about?

`pre-commit run --all-files` runs the same linters we run in CI

**Comment by narendasan** [comment]
> > Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.
> 
> ATenMaxDimConvertsCorrectly was already in the topk tests so I followed that pattern for the rest of the file.

Hmm, can you just move all the min/max tests into test_max.cpp? Not sure why it was put in topk but thats probably confusing.

**Comment by mfeliz-cruise** [comment]
> > > Changes seem fine but some style stuff, why are the converters in max.cpp but the tests in topk.cpp? Also seems like the linter needs to be run on the test code.
> > 
> > 
> > ATenMaxDimConvertsCorrectly was already in the topk tests so I followed that pattern for the rest of the file.
> 
> Hmm, can you just move all the min/max tests into test_max.cpp? Not sure why it was put in topk but thats probably confusing.

I've moved the tests to a new file, test_max.cpp. I'm still seeing a lint failure here, but I'm not seeing any issues running pre-commit locally.

pre-commit run --files core/conversion/converters/impl/max.cpp
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Check for added large files..............................................Passed
Check vcs permalinks.....................................................Passed
Check for merge conflicts................................................Passed
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.............................................................Passed
buildifier...........................................(no files to check)Skipped
buildifier-lint......................................(no files to check)Skipped
NVIDIA-INTERNAL check....................................................Passed

pre-commit run --files tests/core/conversion/converters/BUILD
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Check for added large files..............................................Passed
Check vcs permalinks.....................................................Passed
Check for merge conflicts................................................Passed
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
buildifier...............................................................Passed
buildifier-lint..........................................................Passed
NVIDIA-INTERNAL check....................................................Passed

pre-commit run --files tests/core/conversion/converters/test_max.cpp
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Check for added large files..............................................Passed
Check vcs permalinks.....................................................Passed
Check for merge conflicts................................................Passed
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.............................................................Passed
buildifier...........................................(no files to check)Skipped
buildifier-lint......................................(no files to check)Skipped
NVIDIA-INTERNAL check....................................................Passed

pre-commit run --files tests/core/conversion/converters/test_topk.cpp
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Check for added large files..............................................Passed
Check vcs permalinks.....................................................Passed
Check for merge conflicts................................................Passed
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
clang-format.............................................................Passed
buildifier...........................................(no files to check)Skipped
buildifier-lint......................................(no files to check)Skipped
NVIDIA-INTERNAL check....................................................Passed

**Comment by narendasan** [comment]
Seems like the issue is file permissions: 

```diff
diff --git a/home/runner/work/TensorRT/TensorRT/core/conversion/converters/impl/max.cpp b/tmp/changes.txt
old mode 100755
new mode 100644
ERROR: Some files do not conform to style guidelines
```
Something like 

```sh
chmod 0644 core/conversion/converters/impl/max.cpp
```

**Review by narendasan — APPROVED** [review]
Awesome, LGTM!

**Pull request merged**
