### PR TITLE
Fix errors in unbind and list slice

### PR DESCRIPTION
**Pull request by mfeliz-cruise**
Signed-off-by: Michael Feliz <michael.feliz@getcruise.com>

# Description
Handles negative axis in unbind and None values for start in slice operations on lists.

Fixes # [(issue)](https://github.com/pytorch/TensorRT/issues/1087)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by peri044** [comment]
@mfeliz-cruise Can you please sign the CLA to merge?

**Comment by mfeliz-cruise** [comment]
> @mfeliz-cruise Can you please sign the CLA to merge?

@peri044 The CLA is now signed.

**Comment by peri044** [comment]
@mfeliz-cruise Can you resolve the merge conflicts to merge ?

**Review by narendasan — APPROVED** [review]
LGTM

**Pull request merged**
