### PR TITLE
(//core): Align with prim::Enter in module fallback

### PR DESCRIPTION
**Pull request by andi4191**
Signed-off-by: Anurag Dixit <a.dixit91@gmail.com>

# Description
Aligned with prim::Enter API update in module fallback 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by peri044** [comment]
@andi4191 Can you briefly explain what these changes are doing ? :)

**Comment by andi4191** [comment]
@peri044 : This PR is using a compilation_context node for each prim::Enter and prim::Exit in the segmented blocks to align with the API update in torch. This issue was identified in DLFW staging.

**Comment by andi4191** [comment]
@narendasan @peri044 : Verified this fix working on ToT. Please review.

**Review by narendasan — APPROVED** [review]
LGTM

**Pull request merged**
