### PR TITLE
Clean up AWS credentials

### PR DESCRIPTION
**Pull request by huydhn**
The credential has been revoked to be replaced by OIDC https://github.com/pytorch/test-infra/pull/4865

### CODE REVIEW

**Comment by gs-olive** [comment]
Hi @huydhn - thank you for the PR. Are cases such as the following also affected? These workflows seem to be failing as well on recent runs:
[Failure for below GHA](https://github.com/pytorch/TensorRT/actions/runs/7507098155/job/20442261862)
https://github.com/pytorch/TensorRT/blob/7578fa8b1498e1bfd6fef2bb82dd14476b0f2ecb/.github/workflows/assigner.yml#L27
[Failure for below GHA](https://github.com/pytorch/TensorRT/actions/runs/7497985196/job/20412706420?pr=2575)
https://github.com/pytorch/TensorRT/blob/7578fa8b1498e1bfd6fef2bb82dd14476b0f2ecb/.github/workflows/label.yml#L19

**Comment by huydhn** [comment]
> Hi @huydhn - thank you for the PR. Are cases such as the following also affected? These workflows seem to be failing as well on recent runs: [Failure for below GHA](https://github.com/pytorch/TensorRT/actions/runs/7507098155/job/20442261862)
> 
> https://github.com/pytorch/TensorRT/blob/7578fa8b1498e1bfd6fef2bb82dd14476b0f2ecb/.github/workflows/assigner.yml#L27
> 
> [Failure for below GHA](https://github.com/pytorch/TensorRT/actions/runs/7497985196/job/20412706420?pr=2575)
> 
> https://github.com/pytorch/TensorRT/blob/7578fa8b1498e1bfd6fef2bb82dd14476b0f2ecb/.github/workflows/label.yml#L19

Oh, they need to be fixes, but in a different ways by granting write access to the token.  The context here is that the token default write access has been revoked, so they will need to be grant explicitly.  Let me submit a PR real quick.

**Comment by huydhn** [comment]
@gs-olive This should help fix the issue https://github.com/pytorch/TensorRT/pull/2591

**Comment by gs-olive** [comment]
Great - thank you for adding that PR! Will take a look

**Comment by huydhn** [comment]
Opps, I think I accidentally closed this when merging https://github.com/pytorch/TensorRT/pull/2591, will create another PR to replace this one then

**Pull request merged**
