### PR TITLE
chore: Bump TRT version to 10.2.0.19

### PR DESCRIPTION
**Pull request by zewenli98**
# Description

Bump to TRT 10.2.0.19

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by zewenli98** [comment]
```
ERROR: [Torch-TensorRT TorchScript Conversion Context] - IBuilder::buildSerializedNetwork: Error Code 6: API Usage Error (Unable to load library: libnvinfer_builder_resource_win.so.10.2.0: libnvinfer_builder_resource_win.so.10.2.0: cannot open shared object file: No such file or directory)
```

This error occurred on both CI and my local tests. It seems other users are facing the same error: 
https://github.com/pytorch/TensorRT/issues/2986
https://github.com/NVIDIA/TensorRT/issues/3983

Currently, I noticed there are two solutions to fix the error:
1) downgrade to TRT 10.1
2) pip install tensorrt_llm==0.12.0.dev2024070200

**Comment by HolyWu** [comment]
The Python packages have new `10.2.0.post1` released on 2024/7/9. I'm not sure if it solved that error though.

**Comment by zewenli98** [comment]
> The Python packages have new `10.2.0.post1` released on 2024/7/9. I'm not sure if it solved that error though.

@HolyWu Thanks. I just found the issue is about the package `tensorrt-cu12-libs`. In details,
**`tensorrt-cu12-libs==10.2.0.post1` works fine.** 
`tensorrt-cu12-libs==10.2.0` results in the error and makes tests crashed totally.
`tensorrt-cu12-libs==10.0.1` doesn't cause this error but makes some tests failed.

**Comment by HolyWu** [comment]
10.3.0 is out 🚀

**Comment by zewenli98** [comment]
Close this PR in favor of TRT 10.3 upgrade #3071

**Pull request closed without merging**
