### PR TITLE
feat: keep model's original input signature

### PR DESCRIPTION
**Pull request by bowang007**
Signed-off-by: Bo Wang <bowa@nvidia.com>

# Description

There are some requests that users doesn't want to change the models' inputs signature for input, which could make it difficult to use in a deployment environment. We can keep original inputs signature. 

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by narendasan** [comment]
Does this solution not change the input names anyway?

**Comment by bowang007** [comment]
> Does this solution not change the input names anyway?

yes, that's what we expect.

**Comment by narendasan** [comment]
@bowang007 how does this effect runtime? does this change our convention for providing inputs? I don't think it should but just to make sure

**Comment by bowang007** [comment]
> @bowang007 how does this effect runtime? does this change our convention for providing inputs? I don't think it should but just to make sure

I don't think so.

**Pull request closed without merging**
