### PR TITLE
[FX] remove op_lowering_disallow_list and format revert

### PR DESCRIPTION
**Pull request by frank-wei**
# Description

1. format revert to fb internal to avoid fb code linter issues
2. remove op_lowering_disallow_list

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by narendasan** [comment]
@frank-wei can you share the fb lint config or something so that we can use a consistent code style?

**Comment by frank-wei** [comment]
> @frank-wei can you share the fb lint config or something so that we can use a consistent code style?

They are using black but looks like it is more than that.

**Comment by narendasan** [comment]
> > @frank-wei can you share the fb lint config or something so that we can use a consistent code style?
> 
> 
> 
> They are using black but looks like it is more than that.

This is our current configuration https://github.com/pytorch/TensorRT/blob/master/pyproject.toml

Maybe it's the line width?

**Comment by narendasan** [comment]
Seems like in pytorch/pytorch they dont use the line-length argument. https://github.com/pytorch/pytorch/blob/2c089290b676a221817e48c7de42d1b2bd13609a/pyproject.toml#L22
Can you try commenting it out and seeing if it passes your internal and ours?

**Comment by frank-wei** [comment]
> Seems like in pytorch/pytorch they dont use the line-length argument. https://github.com/pytorch/pytorch/blob/2c089290b676a221817e48c7de42d1b2bd13609a/pyproject.toml#L22 Can you try commenting it out and seeing if it passes your internal and ours?

that is also what I found internally. 
# NOTICE: Python Foundation strongly recommends NOT having
# project-specific configuration. There are many benefits
# to having uniform formatting across every project.  
So the black default uses 88. Let's try default.

**Comment by narendasan** [comment]
Yeah that is fine with me, if the fx changes pass both ours and your internal, I can handle reformatting the rest of the python code

**Comment by narendasan** [comment]
Alternatively if you run `pre-commit run --all-files` you can update the rest of the python files

**Comment by frank-wei** [comment]
@narendasan  could you take a look at the pybind issue in the  `build-x86_64-pyt-nightly`?

**Comment by narendasan** [comment]
> @narendasan could you take a look at the pybind issue in the `build-x86_64-pyt-nightly`?
@peri044 I think you looked at these classes of errors previously on the nightly channel (might have been in another FX pr)

**Review by 842974287 — APPROVED** [review]

**Pull request merged**
