### PR TITLE
feat: Upgrade CUDA to 11.7

### LINKED ISSUE #1432: CUDA 11.7 + Pytorch 1.13 + TRT 8.5  Upgrade
Upgrade to CUDA 11.7 including PyTorch 11.7 CUDA build as well as updating CI Pipelines

### PR DESCRIPTION
**Pull request by peri044**
Signed-off-by: Dheeraj Peri <peri.dheeraj@gmail.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1432 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by peri044** [comment]
Image name in config.yml needs to be updated (image: ubuntu-2004-cuda-11.4:202110-01)

**Comment by Anjum48** [comment]
FYI I managed to build fine this in Ubuntu 22.04 using Bazel 5.20, CUDA 11.7, cudnn 8.5.0.96, TensorRT 8.5.1.7 and Python 3.10.8 (3.11.0 is not yet compatible with ONNX).

The only thing I needed to change was the links in `WORKSPACE` for the CUDA 11.7 versions of libtorch and comment out the sha256 hash. I used local tarballs for cudnn & TensorRT.

I'm not sure if this is an Ubuntu thing, but Bazel couldn't find libdl.so (it might be deprecated?). I did a `whereis libdl.so.2`  and created a symlink (`sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so`)

**Review by narendasan — COMMENTED** [review]
Disable jetson in CI until we can stand up NGC based testing

**Comment by narendasan** [comment]
> FYI I managed to build fine this in Ubuntu 22.04 using Bazel 5.20, CUDA 11.7, cudnn 8.5.0.96, TensorRT 8.5.1.7 and Python 3.10.8 (3.11.0 is not yet compatible with ONNX).
> 
> The only thing I needed to change was the links in `WORKSPACE` for the CUDA 11.7 versions of libtorch and comment out the sha256 hash. I used local tarballs for cudnn & TensorRT.
> 
> I'm not sure if this is an Ubuntu thing, but Bazel couldn't find libdl.so (it might be deprecated?). I did a `whereis libdl.so.2` and created a symlink (`sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so`)

Not sure if something has changed in newer versions of Ubuntu but this line (https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/cpp/bin/torchtrtc/BUILD#L25) just needs to be changed to `-l:ldl`. @peri044 can you include this change in the PR?

**Comment by Anjum48** [comment]
> Not sure if something has changed in newer versions of Ubuntu but this line (
> 
> https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/cpp/bin/torchtrtc/BUILD#L25
> 
> ) just needs to be changed to `-l:ldl`. @peri044 can you include this change in the PR?

@narendasan I gave it a go changing to `ldl` and the build still failed. In the end I just deleted these 3 lines and the build succeeded:

https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/cpp/bin/torchtrtc/BUILD#L24-L26

I believe that Ubuntu 22.04 uses glibc 2.35. According to this [SO answer,](https://unix.stackexchange.com/a/701360) libdl & ldl have been part of the standard library since 2.34

**Comment by narendasan** [comment]
@peri044 there are still tests failing here?

**Comment by peri044** [comment]
> @peri044 there are still tests failing here?

The failing tests are test_stack (whose threshold failure cases are irregular, I've also reduced threshold in a principled way to fix it last week. Passes on my local). 
The other test case was conv3d one which I raised a patch

**Comment by narendasan** [comment]
@peri044 might need to do a bit of work to resolve conflicts here for the enqueue_v3 upgrade (since a bunch of changes went in for the profiler).

**Pull request closed without merging**
