### PR TITLE
upgrade tensorrt dependency to >=10.3.0,<=10.6.0

### PR DESCRIPTION
**Pull request by lanluo-nvidia**
# Description

upgrade tensorrt dependency to >=10.3.0,<=10.6.0

in the docker container: it is always shipped with latest tensorrt 10.6.0

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by narendasan** [comment]
Any idea about the CI issues?

**Review by zewenli98 — COMMENTED** [review]
Can you refer to the previous PR #3071 to make sure the modification is complete?

**Comment by narendasan** [comment]
@zewenli98 can you rebase this branch with main to see if it passes?

**Review by narendasan — APPROVED** [review]
LGTM

**Pull request merged**
