### PR TITLE
support native int64 as valid datatype

### PR DESCRIPTION
**Pull request by apbose**

### CODE REVIEW

**Comment by HolyWu** [comment]
It seems that https://github.com/pytorch/TensorRT/pull/2855/files#diff-97c67f0cea25ec7aa88ca61594d9ad62e9fb575cab3647b079cb718f81308454 is already planned to do relevant changes.

**Comment by apbose** [comment]
Thanks @HolyWu for pointing out the above. @narendasan would the changes in PRhttps://github.com/pytorch/TensorRT/pull/2855/files#diff-97c67f0cea25ec7aa88ca61594d9ad62e9fb575cab3647b079cb718f81308454 work or would we have to create a type map for kINT32 to kINT64 in the torchscript path?

**Comment by narendasan** [comment]
Yeah neither of these PRs implements the feature fully since we need to either amend truncation in TorchScript or have a TorchScript specific type map

**Comment by narendasan** [comment]
@apbose going to close this. reopen a new pr with the comprehensive changes if its still needed

**Pull request closed without merging**
