### PR TITLE
Pass detailed unique layer name to the TRT engine

### LINKED ISSUE #2069: ✨[Feature] Add detailed layer name to the NVTX markers in torch-TRT
**Is your feature request related to a problem? Please describe.**

I use the nsys profiler regularly to study network performance.  One of the important things I need to know is which unique layers map to specific kernels.   There are currently nvtx markers generated by TRT which show some of the layer specific information, but the layer name is not useful.  The layer name is currently unique eg **conv_20** or **mul_40** but it doesn't provide enough context to identify exactly where in the network graph the operator is being executed.   PyTorch provides a mechanism to record the detailed unique name of each nn.module instance.  This name can be pre-fixed to the current operator name to get a unique name which tells you exactly where the node is found in the network architecture.

Example from ResNet
**/layer1/0/conv1/convolution_1**
This shows that the convolution is from the 1st bottleneck block in resnet (/layer1).  Each bottleneck is composed of 2 instances of the same type, implemented using a module list,  this example is instance 0 (layer1/0) .  Then it is the 1st conv (conv1).  Lastly the operator type is a convolution (convolution_1).  With this information it is seldom necessary to inspect the network source code to understand the network architecture.

**Describe the solution you'd like**

Torch-trt is just a pass through for this case.  The module name is created by PyTorch and TensorRT already has NVTX markers.  The only thing needed is for torch-TRT to capture the module name and pass it to TRT.  This layer name is currently passed to TRT here in [run_node()](https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/fx/fx2trt.py#L274) from fx2trt.  The change is just to fetch the module name from pytorch and prefix it to the node name before passing it to TRT.

**Describe alternatives you've considered**

There aren't any good alternatives that I'm aware of.

**Additional context**

Here's an example of what the detailed layer name looks like when it is included in the TRT NVTX markers.  I have already implemented this feature in my local copy of torch-TRT.

torch_trt_detailed_layer_names

### PR DESCRIPTION
**Pull request by alexmsettle**
PyTorch provides a way to retrieve a detailed unique layer name from framework.  The name is derived from the module class hierarchy so details of the network architecture is encoded in the name.  This information is really useful for performance analysis and for a basic understanding of the network architecture.  The goal is to pass this name from PyTorch to TRT, torch-TRT is effectively just a pass through stage. 

# Description
Each layer in pytorch is defined by classes which inherit from nn.module.  The fx graph represents the network as a sequence of nn.module instances along with the pytorch operators which implement the forward method for each class.  Each of these operators can be made unique by prefixing them with the module name they appear in.  The fx graph maintains the module name in the node.meta['nn_module_stack'] attribute.  This change just fetches the 'nn_module_stack' cleans up the name and prefixes it to the operator name, then it gets passed to the TRT engine IR.

Fixes #2069

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Comment by alexmsettle** [comment]
@narendasan  - how do you run the linter locally?

**Review by gs-olive — COMMENTED** [review]
Overall, augmenting the node name to include the critical module-path information is very useful in debugging models. Pending the Python style linting via pre-commit:
```bash
pip install -r requirements-dev.txt 
pre-commit install
```

**Comment by gs-olive** [comment]
@alexmsettle - could you remove the changes to `py/torch_tensorrt/fx/fx2trt.py` and leave only those to `py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py`? Afterwards, I think it should be good to go!

**Comment by peri044** [comment]
Closing this in favor of https://github.com/pytorch/TensorRT/pull/2162. Please post there for further questions.

**Pull request closed without merging**
