### PR TITLE
Conv3d patch for 1.3 release

### PR DESCRIPTION
**Pull request by peri044**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by yinghai — COMMENTED** [review]
Do we also need to disable all the conv3d tests due to https://github.com/pytorch/TensorRT/issues/1445?

**Comment by narendasan** [comment]
> Do we also need to disable all the conv3d tests due to #1445?

I think we only need to disable the kernel_size 1 test. This should be disabled in both PRs

**Comment by frank-wei** [comment]
The test failed for groups=3 and kernel=1 but other tests with kernel=1 look good. https://github.com/pytorch/TensorRT/blob/master/py/torch_tensorrt/fx/test/converters/vanilla/test_convolution_vanilla.py#L79-L83
Just curious, is the kernel=1 be the reason or groups=3 be the reason? @peri044

**Comment by peri044** [comment]
> The test failed for groups=3 and kernel=1 but other tests with kernel=1 look good. https://github.com/pytorch/TensorRT/blob/master/py/torch_tensorrt/fx/test/converters/vanilla/test_convolution_vanilla.py#L79-L83 Just curious, is the kernel=1 be the reason or groups=3 be the reason? @peri044

This error happens when this is true  -  is_3d_conv && filter.depth == 1 && (input.depth != 1 || output.depth  != 1)
We have an internal fix for this issue and this will probably land in the next minor or patch release.

**Comment by narendasan** [comment]
redirect this PR into #1485 and use that PR to get it into release/1.3, that way we can show correctness for both PRs

**Comment by peri044** [comment]
Closing this since it is merged in #1485

**Pull request closed without merging**
