### PR TITLE
feat: support cumsum dynamo converter

### PR DESCRIPTION
**Pull request by zewenli98**
# Description

Support `cumsum` dynamo converter. This is a part of `slice` converter.

Fixes part of #2215 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

### CODE REVIEW

**Review by gs-olive — COMMENTED** [review]
Added minor comments, otherwise looks good!

**Comment by zewenli98** [comment]
Thanks for the comments! They have been fixed!

**Review by gs-olive — APPROVED** [review]
Looks good to me! Please rebase once #2418 is merged, and then ensure this PR also passes all of CI.

**Comment by zewenli98** [comment]
Got errors:
```
FAILED models/test_export_serde.py::test_base_full_compile - TypeError: __init__() got an unexpected keyword argument 'parameters'
FAILED models/test_export_serde.py::test_base_full_compile_multiple_outputs - TypeError: __init__() got an unexpected keyword argument 'parameters'
FAILED models/test_export_serde.py::test_base_full_compile_save_load - TypeError: __init__() got an unexpected keyword argument 'parameters'
FAILED models/test_export_serde.py::test_hybrid_relu_fallback - TypeError: __init__() got an unexpected keyword argument 'parameters'
FAILED models/test_export_serde.py::test_resnet18_save_load - KeyError: 'parameter name can\'t contain "."'
```

Can we merge it now? or waiting for a fix to this bug?

**Comment by gs-olive** [comment]
I think it can be merged while that fix is in progress, since it passes all of the newly added tests in CI and none of those models would invoke this specific converter.

**Pull request merged**
